"""Keyword-based category hints used before LLM classification."""

from __future__ import annotations

from typing import Dict, List


CATEGORY_ORDER = [
    "Transportation",
    "Taxes",
    "Health",
    "Technology",
    "Office",
    "Services",
    "Home",
    "Food",
]

CATEGORY_KEYWORDS: Dict[str, List[str]] = {
    # Use English keywords exclusively so downstream classification remains language-consistent.
    "Food": [
        "supermarket",
        "food",
        "restaurant",
        "delivery",
        "menu",
        "beverage",
        "soda",
        "coffee",
        "bread",
        "meat",
        "chicken",
        "vegetable",
        "fruit",
        "snack",
        "pizza",
        "burger",
        "sushi",
        "grocery",
    ],
    "Technology": [
        "laptop",
        "notebook",
        "pc",
        "ssd",
        "hdd",
        "ram",
        "monitor",
        "screen",
        "mouse",
        "keyboard",
        "usb",
        "cable",
        "adapter",
        "charger",
        "headphones",
        "headset",
        "smartphone",
        "cellphone",
        "tablet",
        "router",
        "modem",
        "software",
        "license",
    ],
    "Office": [
        "paper",
        "ream",
        "ink",
        "toner",
        "printer",
        "pen",
        "ballpoint",
        "marker",
        "notebook",
        "folder",
        "envelope",
        "stapler",
        "staples",
        "clip",
        "ruler",
        "scissors",
        "planner",
        "stamp",
    ],
    "Transportation": [
        "gasoline",
        "fuel",
        "diesel",
        "toll",
        "parking",
        "ticket",
        "taxi",
        "uber",
        "cabify",
        "car service",
        "subway",
        "train",
        "bus",
    ],
    "Services": [
        "internet",
        "fiber",
        "wifi",
        "phone",
        "plan",
        "hosting",
        "domain",
        "cloud",
        "maintenance",
        "support",
        "subscription",
        "renewal",
        "technical service",
        "electricity",
        "power",
        "water",
        "gas",
    ],
    "Taxes": [
        "vat",
        "tax",
        "taxes",
        "withholding",
        "perception",
        "assessment",
        "municipal",
        "federal",
        "state tax",
    ],
    "Health": [
        "pharmacy",
        "medicine",
        "medication",
        "consultation",
        "doctor",
        "clinic",
        "laboratory",
        "dentistry",
        "dentist",
        "optical",
        "glasses",
    ],
    "Home": [
        "cleaning",
        "detergent",
        "bleach",
        "soap",
        "sponge",
        "furniture",
        "lamp",
        "bulb",
        "paint",
        "hardware",
        "tool",
        "decor",
    ],
}

VENDOR_HINTS: Dict[str, str] = {
    "uber": "Transportation",
    "cabify": "Transportation",
    "movistar": "Services",
    "personal": "Services",
    "claro": "Services",
    "ypf": "Transportation",
    "shell": "Transportation",
    "axion": "Transportation",
    "pharmacy": "Health",
    "optical": "Health",
}
