"""Keyword-based category hints used before Groq classification."""

from __future__ import annotations

from typing import Dict, List


CATEGORY_ORDER = [
    "Transporte",
    "Impuestos",
    "Salud",
    "Tecnologia",
    "Oficina",
    "Servicios",
    "Hogar",
    "Alimentos",
]

CATEGORY_KEYWORDS: Dict[str, List[str]] = {
    "Alimentos": [
        "supermercado",
        "comida",
        "restaurante",
        "delivery",
        "menu",
        "bebida",
        "gaseosa",
        "cafe",
        "pan",
        "carne",
        "pollo",
        "verdura",
        "fruta",
        "snack",
        "pizza",
        "hamburguesa",
        "sushi",
        "grocery",
    ],
    "Tecnologia": [
        "laptop",
        "notebook",
        "pc",
        "ssd",
        "hdd",
        "ram",
        "monitor",
        "pantalla",
        "mouse",
        "teclado",
        "usb",
        "cable",
        "adaptador",
        "cargador",
        "auriculares",
        "headset",
        "smartphone",
        "celular",
        "tablet",
        "router",
        "modem",
        "software",
        "licencia",
    ],
    "Oficina": [
        "papel",
        "resma",
        "tinta",
        "toner",
        "impresora",
        "lapicera",
        "boligrafo",
        "marcador",
        "cuaderno",
        "carpeta",
        "sobre",
        "engrampadora",
        "grapas",
        "clip",
        "regla",
        "tijera",
        "agenda",
        "sello",
    ],
    "Transporte": [
        "nafta",
        "combustible",
        "gasolina",
        "diesel",
        "peaje",
        "estacionamiento",
        "parking",
        "pasaje",
        "taxi",
        "uber",
        "cabify",
        "remis",
        "subte",
        "tren",
        "bus",
    ],
    "Servicios": [
        "internet",
        "fibra",
        "wifi",
        "telefonia",
        "plan",
        "hosting",
        "dominio",
        "cloud",
        "mantenimiento",
        "soporte",
        "suscripcion",
        "subscription",
        "renovacion",
        "servicio tecnico",
        "electricidad",
        "luz",
        "agua",
        "gas",
    ],
    "Impuestos": [
        "iva",
        "vat",
        "tax",
        "impuesto",
        "ingresos brutos",
        "monotributo",
        "ganancias",
        "percepcion",
        "retencion",
        "tasa",
        "municipal",
        "afip",
    ],
    "Salud": [
        "farmacia",
        "medicamento",
        "medicacion",
        "consulta",
        "medico",
        "clinica",
        "laboratorio",
        "odontologia",
        "dentista",
        "optica",
        "lentes",
    ],
    "Hogar": [
        "limpieza",
        "detergente",
        "lavandina",
        "jabon",
        "esponja",
        "mueble",
        "lampara",
        "bombilla",
        "pintura",
        "ferreteria",
        "herramienta",
        "decoracion",
    ],
}

VENDOR_HINTS: Dict[str, str] = {
    "uber": "Transporte",
    "cabify": "Transporte",
    "movistar": "Servicios",
    "personal": "Servicios",
    "claro": "Servicios",
    "ypf": "Transporte",
    "shell": "Transporte",
    "axion": "Transporte",
    "farmacia": "Salud",
    "optica": "Salud",
}
